services:
  verif:
    image: ghcr.io/hdl/sim/osvb
    volumes:
      - ./:/code
    working_dir: /code/rundir/
    command: >
      sh -c "echo 'Compiling...'
             iverilog -g2012 /code/rtl/*.sv /code/verif/*.sv
             echo 'Executing...'
             vvp a.out"

  synth:
    image: ghcr.io/hdl/impl/pnr
    volumes:
      - ./:/code
    command: yosys -s /code/synth_script/synth.tcl -l /code/rundir/synth.log
